import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        layout: {
          socialButtonsVariant: "blockButton",
        },
        variables: {
          colorPrimary: "#0369a1",
          colorTextOnPrimaryBackground: "white",
        },
        elements: {
          card: "shadow-xl",
          modalBackdrop: "backdrop-blur-md",
          headerTitle: "text-2xl font-bold",
          formButtonPrimary: "rounded-full",
          formButtonSecondary: "rounded-full",
          socialButtonsIconButton: "rounded-full",
          socialButtonsBlockButton: "rounded-full",
          formFieldInput: "rounded-full",
          formFieldInputGroup: "rounded-full",
        },
      }}
    >
      <html lang="en">
        <body className={`${roboto.variable} font-sans antialiased`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
