import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        layout: {
          socialButtonsVariant: "blockButton",
        },
        variables: {
          colorPrimary: "#0369a1",
          colorTextOnPrimaryBackground: "white",
        },
        elements: {
          card: "shadow-xl",
          modalBackdrop: "backdrop-blur-md",
          headerTitle: "text-2xl",
          formButtonPrimary: "rounded-full",
          formButtonSecondary: "rounded-full",
          socialButtonsIconButton: "rounded-full",
          socialButtonsBlockButton: "rounded-full",
          formFieldInput: "rounded-full",
          formFieldInputGroup: "rounded-full",
        },
      }}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
